#
# Module manifest for module 'veTools'
#
# Generated by: Or Idgar
#
# Generated on: 8/19/2015
#

@{

# Script module or binary module file associated with this manifest.
# previously known as ModuleToProcess
#RootModule = 'veTools'

# Version number of this module.
ModuleVersion = '0.62'

# ID used to uniquely identify this module
GUID = '8e4812d5-51dd-460c-9a03-ecef75adf182'

# Author of this module
Author = 'Or Idgar'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 Or Idgar. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# For that all the psm1 files needs to be in the same folder - veTools folder. the problem is that all the functions will be seen as vetools commands
# and not as independent module.
# see http://stackoverflow.com/questions/16424171/create-a-manifest-for-nested-powershell-modules
NestedModules = @('veTools.Ato','veTools.Common','veTools.LabManager','veTools.Maintain','veTools','veTools.Rep','veTools.vcdRestAPI')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

